/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.TextField;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
/**
 *
 * @author ifonsecaz
 */
public class SudokuVista extends java.awt.Frame {

    private static TextField[][] campos;
    private SudokuR a;
    /**
     * Creates new form SudokuVista
     */
    public SudokuVista() {
        initComponents();
        campos=new TextField[9][9];
        
        campos[0][0]=tF1;
        campos[0][1]=tF2;
        campos[0][2]=tF3;
        campos[1][0]=tF4;
        campos[1][1]=tF5;
        campos[1][2]=tF6;
        campos[2][0]=tF7;
        campos[2][1]=tF8;
        campos[2][2]=tF9;
        campos[0][3]=tF10;
        campos[0][4]=tF11;
        campos[0][5]=tF12;
        campos[1][3]=tF13;
        campos[1][4]=tF14;
        campos[1][5]=tF15;
        campos[2][3]=tF16;
        campos[2][4]=tF17;
        campos[2][5]=tF18;
        campos[0][6]=tF19;
        campos[0][7]=tF20;
        campos[0][8]=tF21;
        campos[1][6]=tF22;
        campos[1][7]=tF23;
        campos[1][8]=tF24;
        campos[2][6]=tF25;
        campos[2][7]=tF26;
        campos[2][8]=tF27;
        campos[3][0]=tF28;
        campos[3][1]=tF29;
        campos[3][2]=tF30;
        campos[4][0]=tF31;
        campos[4][1]=tF32;
        campos[4][2]=tF33;
        campos[5][0]=tF34;
        campos[5][1]=tF35;
        campos[5][2]=tF36;
        campos[3][3]=tF37;
        campos[3][4]=tF38;
        campos[3][5]=tF39;
        campos[4][3]=tF40;
        campos[4][4]=tF41;
        campos[4][5]=tF42;
        campos[5][3]=tF43;
        campos[5][4]=tF44;
        campos[5][5]=tF45;
        campos[3][6]=tF46;
        campos[3][7]=tF47;
        campos[3][8]=tF48;
        campos[4][6]=tF49;
        campos[4][7]=tF50;
        campos[4][8]=tF51;
        campos[5][6]=tF52;
        campos[5][7]=tF53;
        campos[5][8]=tF54;
        campos[6][0]=tF55;
        campos[6][1]=tF56;
        campos[6][2]=tF57;
        campos[7][0]=tF58;
        campos[7][1]=tF59;
        campos[7][2]=tF60;
        campos[8][0]=tF61;
        campos[8][1]=tF62;
        campos[8][2]=tF63;
        campos[6][3]=tF64;
        campos[6][4]=tF65;
        campos[6][5]=tF66;
        campos[7][3]=tF67;
        campos[7][4]=tF68;
        campos[7][5]=tF69;
        campos[8][3]=tF70;
        campos[8][4]=tF71;
        campos[8][5]=tF72;
        campos[6][6]=tF73;
        campos[6][7]=tF74;
        campos[6][8]=tF75;
        campos[7][6]=tF76;
        campos[7][7]=tF77;
        campos[7][8]=tF78;
        campos[8][6]=tF79;
        campos[8][7]=tF80;
        campos[8][8]=tF81;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        textField1 = new java.awt.TextField();
        jPanel3 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        tF1 = new java.awt.TextField();
        tF2 = new java.awt.TextField();
        tF3 = new java.awt.TextField();
        tF4 = new java.awt.TextField();
        tF5 = new java.awt.TextField();
        tF6 = new java.awt.TextField();
        tF7 = new java.awt.TextField();
        tF8 = new java.awt.TextField();
        tF9 = new java.awt.TextField();
        tF10 = new java.awt.TextField();
        tF11 = new java.awt.TextField();
        tF12 = new java.awt.TextField();
        tF13 = new java.awt.TextField();
        tF14 = new java.awt.TextField();
        tF15 = new java.awt.TextField();
        tF16 = new java.awt.TextField();
        tF17 = new java.awt.TextField();
        tF18 = new java.awt.TextField();
        tF19 = new java.awt.TextField();
        tF20 = new java.awt.TextField();
        tF21 = new java.awt.TextField();
        tF22 = new java.awt.TextField();
        tF23 = new java.awt.TextField();
        tF24 = new java.awt.TextField();
        tF25 = new java.awt.TextField();
        tF26 = new java.awt.TextField();
        tF27 = new java.awt.TextField();
        tF28 = new java.awt.TextField();
        tF29 = new java.awt.TextField();
        tF30 = new java.awt.TextField();
        tF31 = new java.awt.TextField();
        tF32 = new java.awt.TextField();
        tF33 = new java.awt.TextField();
        tF34 = new java.awt.TextField();
        tF35 = new java.awt.TextField();
        tF36 = new java.awt.TextField();
        tF37 = new java.awt.TextField();
        tF38 = new java.awt.TextField();
        tF39 = new java.awt.TextField();
        tF40 = new java.awt.TextField();
        tF41 = new java.awt.TextField();
        tF42 = new java.awt.TextField();
        tF43 = new java.awt.TextField();
        tF44 = new java.awt.TextField();
        tF45 = new java.awt.TextField();
        tF46 = new java.awt.TextField();
        tF47 = new java.awt.TextField();
        tF48 = new java.awt.TextField();
        tF49 = new java.awt.TextField();
        tF50 = new java.awt.TextField();
        tF51 = new java.awt.TextField();
        tF52 = new java.awt.TextField();
        tF53 = new java.awt.TextField();
        tF54 = new java.awt.TextField();
        tF55 = new java.awt.TextField();
        tF56 = new java.awt.TextField();
        tF57 = new java.awt.TextField();
        tF58 = new java.awt.TextField();
        tF59 = new java.awt.TextField();
        tF60 = new java.awt.TextField();
        tF61 = new java.awt.TextField();
        tF62 = new java.awt.TextField();
        tF63 = new java.awt.TextField();
        tF64 = new java.awt.TextField();
        tF65 = new java.awt.TextField();
        tF66 = new java.awt.TextField();
        tF67 = new java.awt.TextField();
        tF68 = new java.awt.TextField();
        tF69 = new java.awt.TextField();
        tF70 = new java.awt.TextField();
        tF71 = new java.awt.TextField();
        tF72 = new java.awt.TextField();
        tF73 = new java.awt.TextField();
        tF74 = new java.awt.TextField();
        tF75 = new java.awt.TextField();
        tF76 = new java.awt.TextField();
        tF77 = new java.awt.TextField();
        tF78 = new java.awt.TextField();
        tF79 = new java.awt.TextField();
        tF80 = new java.awt.TextField();
        tF81 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        jInternalFrame1.setVisible(true);

        textField1.setText("textField1");

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationRelativeTo(jPanel1);
        setPreferredSize(new java.awt.Dimension(440, 440));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        label1.setText("Sudoku");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 40));

        tF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF1ActionPerformed(evt);
            }
        });
        add(tF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        add(tF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        add(tF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        add(tF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        tF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF5ActionPerformed(evt);
            }
        });
        add(tF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        add(tF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        add(tF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        add(tF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        tF9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF9ActionPerformed(evt);
            }
        });
        add(tF9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        tF10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF10ActionPerformed(evt);
            }
        });
        add(tF10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));
        add(tF11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        add(tF12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));
        add(tF13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        add(tF14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
        add(tF15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));
        add(tF16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));
        add(tF17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        tF18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF18ActionPerformed(evt);
            }
        });
        add(tF18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        tF19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF19ActionPerformed(evt);
            }
        });
        add(tF19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));
        add(tF20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));
        add(tF21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));
        add(tF22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        add(tF23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));
        add(tF24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));
        add(tF25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));
        add(tF26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        tF27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF27ActionPerformed(evt);
            }
        });
        add(tF27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        tF28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF28ActionPerformed(evt);
            }
        });
        add(tF28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        add(tF29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        add(tF30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));
        add(tF31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        add(tF32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        add(tF33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        add(tF34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        add(tF35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        tF36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF36ActionPerformed(evt);
            }
        });
        add(tF36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        tF37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF37ActionPerformed(evt);
            }
        });
        add(tF37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));
        add(tF38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));
        add(tF39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));
        add(tF40, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        add(tF41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));
        add(tF42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
        add(tF43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        add(tF44, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        tF45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF45ActionPerformed(evt);
            }
        });
        add(tF45, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        tF46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF46ActionPerformed(evt);
            }
        });
        add(tF46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
        add(tF47, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));
        add(tF48, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));
        add(tF49, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        add(tF50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));
        add(tF51, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));
        add(tF52, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));
        add(tF53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        tF54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF54ActionPerformed(evt);
            }
        });
        add(tF54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        tF55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF55ActionPerformed(evt);
            }
        });
        add(tF55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        add(tF56, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));
        add(tF57, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));
        add(tF58, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));
        add(tF59, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
        add(tF60, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));
        add(tF61, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));
        add(tF62, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        tF63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF63ActionPerformed(evt);
            }
        });
        add(tF63, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        tF64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF64ActionPerformed(evt);
            }
        });
        add(tF64, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));
        add(tF65, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));
        add(tF66, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));
        add(tF67, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));
        add(tF68, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));
        add(tF69, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));
        add(tF70, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));
        add(tF71, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        tF72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF72ActionPerformed(evt);
            }
        });
        add(tF72, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        tF73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF73ActionPerformed(evt);
            }
        });
        add(tF73, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));
        add(tF74, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));
        add(tF75, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));
        add(tF76, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));
        add(tF77, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));
        add(tF78, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));
        add(tF79, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));
        add(tF80, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        tF81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tF81ActionPerformed(evt);
            }
        });
        add(tF81, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        button1.setLabel("Limpiar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button2.setLabel("Resolver");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void tF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF1ActionPerformed

    private void tF9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF9ActionPerformed

    private void tF10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF10ActionPerformed

    private void tF18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF18ActionPerformed

    private void tF19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF19ActionPerformed

    private void tF27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF27ActionPerformed

    private void tF28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF28ActionPerformed

    private void tF36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF36ActionPerformed

    private void tF37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF37ActionPerformed

    private void tF45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF45ActionPerformed

    private void tF46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF46ActionPerformed

    private void tF54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF54ActionPerformed

    private void tF55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF55ActionPerformed

    private void tF63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF63ActionPerformed

    private void tF64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF64ActionPerformed

    private void tF72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF72ActionPerformed

    private void tF73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF73ActionPerformed

    private void tF81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF81ActionPerformed

    /**<pre>
     * Resolver
     * 
     * Intenta resolver el problema, primero agrega los números dados por el usuario a la matriz e intenta resolverlo
     * De hallar la solución rellenará los textField de la vista, de lo contrario mostrará un mensaje.
     * </pre>
     * @param evt 
     */
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        a= new SudokuR();
        
        agregaNum(0,0);
        
        if(a.solucionador()){
            rellena(0,0);
        }
        else{
            JOptionPane.showMessageDialog(null, "No tiene solución");
        }
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * <pre>
     * Limpiar
     * 
     * Llama al método recursivo del mismo nombre para vaciar las celdas del sudoku
     * </pre>
     * @param evt 
     */
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        limpiar(0,0);
    }//GEN-LAST:event_button1ActionPerformed

    private void tF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tF5ActionPerformed

    /**<pre>
     * Recorre cada TextField y agrega un String vacío
     * 
     * @param i Renglones
     * @param j Columnas
     * </pre>
     */
    private static void limpiar(int i,int j){
        if(i<9){
            if(j<9){
                campos[i][j].setText("");
                limpiar(i,j+1);
            }
            else{
                limpiar(i+1,0);
            }
        }
    }
    
    /**
     * <pre>
     * De la matriz del objeto saca cada número y lo pone en su correspondiente JTextField, para que la solución se muestre al usuario
     * @param i Renglones
     * @param j Columnas
     * </pre>
     */
    private void rellena(int i, int j){
        if(i<9){
            if(j<9){
                campos[i][j].setText("" + a.getNum(i, j));
                rellena(i,j+1);
            }
            else{
                rellena(i+1,0);
            }
        }
    }
    
    /**
     * <pre>
     * Pasa por cada JTextField y toma los números insertados por el usuario, asegurándose sean válidos, de lo contrario muestra un mensaje
     * @param i Renglones
     * @param j Columnas
     * </pre>
     */
    private void agregaNum(int i, int j){
        if(i<9){
            if(j<9){
                if(!campos[i][j].getText().equals("")){
                    int num=Integer.parseInt(campos[i][j].getText());
                    if(a.revisa(i, j, num)){
                         a.altaNum(num, i, j);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Asegurate de introducir correctamente los números");
                    }
                }
                agregaNum(i,j+1);
            }
            else{
                agregaNum(i+1,0);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuVista().setVisible(true);
                limpiar(0,0);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.TextField tF1;
    private java.awt.TextField tF10;
    private java.awt.TextField tF11;
    private java.awt.TextField tF12;
    private java.awt.TextField tF13;
    private java.awt.TextField tF14;
    private java.awt.TextField tF15;
    private java.awt.TextField tF16;
    private java.awt.TextField tF17;
    private java.awt.TextField tF18;
    private java.awt.TextField tF19;
    private java.awt.TextField tF2;
    private java.awt.TextField tF20;
    private java.awt.TextField tF21;
    private java.awt.TextField tF22;
    private java.awt.TextField tF23;
    private java.awt.TextField tF24;
    private java.awt.TextField tF25;
    private java.awt.TextField tF26;
    private java.awt.TextField tF27;
    private java.awt.TextField tF28;
    private java.awt.TextField tF29;
    private java.awt.TextField tF3;
    private java.awt.TextField tF30;
    private java.awt.TextField tF31;
    private java.awt.TextField tF32;
    private java.awt.TextField tF33;
    private java.awt.TextField tF34;
    private java.awt.TextField tF35;
    private java.awt.TextField tF36;
    private java.awt.TextField tF37;
    private java.awt.TextField tF38;
    private java.awt.TextField tF39;
    private java.awt.TextField tF4;
    private java.awt.TextField tF40;
    private java.awt.TextField tF41;
    private java.awt.TextField tF42;
    private java.awt.TextField tF43;
    private java.awt.TextField tF44;
    private java.awt.TextField tF45;
    private java.awt.TextField tF46;
    private java.awt.TextField tF47;
    private java.awt.TextField tF48;
    private java.awt.TextField tF49;
    private java.awt.TextField tF5;
    private java.awt.TextField tF50;
    private java.awt.TextField tF51;
    private java.awt.TextField tF52;
    private java.awt.TextField tF53;
    private java.awt.TextField tF54;
    private java.awt.TextField tF55;
    private java.awt.TextField tF56;
    private java.awt.TextField tF57;
    private java.awt.TextField tF58;
    private java.awt.TextField tF59;
    private java.awt.TextField tF6;
    private java.awt.TextField tF60;
    private java.awt.TextField tF61;
    private java.awt.TextField tF62;
    private java.awt.TextField tF63;
    private java.awt.TextField tF64;
    private java.awt.TextField tF65;
    private java.awt.TextField tF66;
    private java.awt.TextField tF67;
    private java.awt.TextField tF68;
    private java.awt.TextField tF69;
    private java.awt.TextField tF7;
    private java.awt.TextField tF70;
    private java.awt.TextField tF71;
    private java.awt.TextField tF72;
    private java.awt.TextField tF73;
    private java.awt.TextField tF74;
    private java.awt.TextField tF75;
    private java.awt.TextField tF76;
    private java.awt.TextField tF77;
    private java.awt.TextField tF78;
    private java.awt.TextField tF79;
    private java.awt.TextField tF8;
    private java.awt.TextField tF80;
    private java.awt.TextField tF81;
    private java.awt.TextField tF9;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
